Offset results
luuuk/screwthereview-server pull request #12
Opened 2021-05-11 20:10 UTC by luuuk

2021-05-11 20:56 UTC, mackenzieleach commented on src/app.js
> +const whitelist = ['http://localhost:3000', 'https://screwthereview.netlify.app'];
I also have Auth0 configured to support ports 3001 and 3002 for a little more flexibility for windows users - sometimes we have to use a different port or restart out laptops to kill the process if we haven't restarted between dev sessions. May be a good thing to add to the whitelist for consistency

2021-05-11 20:59 UTC, mackenzieleach requested changes
Just a couple of things to add for consistency with ports on Auth0 and one comment to add!

2021-05-11 21:57 UTC, luuuk reviewed
@mackenzieleach made changes addressing your comments, can you approve?

2021-05-11 23:10 UTC, mackenzieleach approved these changes

2021-05-12 05:58 UTC, mackenzieleach approved these changes

2021-05-12 05:58 UTC, merged